### ISSUE TITLE
Missing import in Colab 

### ISSUE THREAD

**Issue by LionThu1** [dptech-corp/Uni-Fold#115] opened 2023-04-20 18:56 UTC
The provided Colab will break at the generate MSAs step, due to the libmsym package missing. 

Installing the missing package via pip3 solves the issue for me.

Might confuse someone through.

**Comment by ZiyaoLi** [comment] 2023-04-23 08:37
thanks for the feedback.

this issue is caused by the addition code of uni-fold au extraction.

issue again mentioned in #116 and fixed in #117.

**Closed** 2023-04-23 08:37 UTC
